linters:
  enable:
  - asciicheck
  - bidichk
  - bodyclose
  - containedctx
  - contextcheck
  - deadcode
  - decorder
  - depguard
  - dogsled
  - dupl
  - durationcheck
  - errcheck
  - errchkjson
  - errname
  - errorlint
  - exhaustive
  - exportloopref
  - forcetypeassert
  - goconst
  - gocritic
  - goerr113
  - gofmt
  - goimports
  - gomodguard
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - grouper
  - importas
  - ineffassign
  - ireturn
  - misspell
  - nakedret
  - nilerr
  - noctx
  - nonamedreturns
  - nosprintfhostport
  - prealloc
  - predeclared
  - staticcheck
  - structcheck
  - tagliatelle
  - tenv
  - thelper
  - typecheck
  - unconvert
  - unparam
  - unused
  - varcheck
  - wastedassign
  disable:
  - cyclop
  - execinquery
  - exhaustivestruct
  - exhaustruct
  - funlen
  - gci
  - gochecknoglobals
  - gochecknoinits
  - gocognit
  - gocyclo
  - godox
  - gofumpt
  - goheader
  - gomnd
  - gomoddirectives
  - ifshort
  - lll
  - maintidx
  - makezero
  - nestif
  - nlreturn
  - nlreturn
  - nolintlint
  - paralleltest
  - promlinter
  - revive
  - rowserrcheck
  - scopelint
  - sqlclosecheck
  - testpackage
  - tparallel
  - varnamelen
  - wrapcheck
  - whitespace
  - wsl

linters-settings:
  goimports:
    local-prefixes: github.com/rockwell-uk/go-shpconvert
  gosec:
    config:
      G306: "0644"
  errorlint:
    errorf: false

issues:
  exclude-rules:
  - linters:
    - goerr113
    text: "do not define dynamic errors, use wrapped static errors instead"
